-- Esquema de Base de Datos v2: MONITOREO-COM
-- Fecha de Actualización: 24/10/2025

-- Este script contiene la estructura completa y actualizada de la base de datos,
-- incluyendo las nuevas tablas de Alertas, Auditoría, Configuración y Notificaciones,
-- y la adición del campo de versión de firmware en la tabla HOST.
-- Se ha añadido el prefijo TB_ a todas las tablas.

-- --- Tablas de Catálogo (Datos Maestros) ---

CREATE TABLE TB_GERENCIA (
    ID_GERENCIA INTEGER PRIMARY KEY,
    NOM_GERENCIA TEXT NOT NULL
);

CREATE TABLE TB_AREA (
    ID_AREA INTEGER PRIMARY KEY,
    NOM_AREA TEXT NOT NULL,
    ID_GERENCIA INTEGER NOT NULL,
    FOREIGN KEY (ID_GERENCIA) REFERENCES TB_GERENCIA(ID_GERENCIA)
);

CREATE TABLE TB_PROCESO (
    ID_PROCESO INTEGER PRIMARY KEY,
    NOM_PROCESO TEXT NOT NULL,
    DET_PROCESO TEXT
);

CREATE TABLE TB_SEDE (
    ID_SEDE INTEGER PRIMARY KEY,
    NOM_SEDE TEXT NOT NULL
);

CREATE TABLE TB_UBICACION (
    ID_UBICACION INTEGER PRIMARY KEY,
    NOM_UBICACION TEXT NOT NULL,
    COORD_UBICACION TEXT,
    ID_SEDE INTEGER NOT NULL,
    FOREIGN KEY (ID_SEDE) REFERENCES TB_SEDE(ID_SEDE)
);

CREATE TABLE TB_CATEGORIA (
    ID_CATEGORIA INTEGER PRIMARY KEY,
    NOM_CATEGORIA TEXT NOT NULL
);

CREATE TABLE TB_MARCA (
    ID_MARCA INTEGER PRIMARY KEY,
    NOM_MARCA TEXT NOT NULL
);

CREATE TABLE TB_MODELO (
    ID_MODELO INTEGER PRIMARY KEY,
    NOM_MODELO TEXT NOT NULL,
    ID_MARCA INTEGER NOT NULL,
    FOREIGN KEY (ID_MARCA) REFERENCES TB_MARCA(ID_MARCA)
);

CREATE TABLE TB_RESPONSABLE (
    ID_RESPONSABLE INTEGER PRIMARY KEY,
    NOM_RESPONSABLE TEXT NOT NULL,
    ID_AREA INTEGER NOT NULL,
    FOREIGN KEY (ID_AREA) REFERENCES TB_AREA(ID_AREA)
);

CREATE TABLE TB_ESTADO (
    ID_ESTADO INTEGER PRIMARY KEY,
    NOM_ESTADO TEXT NOT NULL UNIQUE
);

CREATE TABLE TB_USUARIOS_DEL_SISTEMA (
    ID_USUARIO INTEGER PRIMARY KEY,
    NOM_USUARIO TEXT NOT NULL UNIQUE,
    PASSWORD_HASH TEXT NOT NULL,
    ROL TEXT NOT NULL
);

-- --- Tablas Transaccionales (Datos Variables) ---

CREATE TABLE TB_HOST (
    ID_HOST INTEGER PRIMARY KEY,
    NOM_HOST TEXT NOT NULL,
    IP_HOST TEXT NOT NULL UNIQUE,
    MAC_HOST TEXT,
    NUM_SERIE TEXT,
    FIRMWARE_VERSION TEXT, -- Campo nuevo
    FECHA_ALTA DATE,
    AÑO_ALTA INTEGER,
    ID_MODELO INTEGER NOT NULL,
    ID_RESPONSABLE INTEGER NOT NULL,
    ID_UBICACION INTEGER NOT NULL,
    ID_PROCESO INTEGER NOT NULL,
    ID_CATEGORIA INTEGER NOT NULL,
    ID_ESTADO INTEGER NOT NULL,
    LIM_SUP_PING REAL,
    LIM_INF_PING REAL,
    FOREIGN KEY (ID_MODELO) REFERENCES TB_MODELO(ID_MODELO),
    FOREIGN KEY (ID_RESPONSABLE) REFERENCES TB_RESPONSABLE(ID_RESPONSABLE),
    FOREIGN KEY (ID_UBICACION) REFERENCES TB_UBICACION(ID_UBICACION),
    FOREIGN KEY (ID_PROCESO) REFERENCES TB_PROCESO(ID_PROCESO),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES TB_CATEGORIA(ID_CATEGORIA),
    FOREIGN KEY (ID_ESTADO) REFERENCES TB_ESTADO(ID_ESTADO)
);

CREATE TABLE TB_MONITOREO (
    ID_MONITOREO INTEGER PRIMARY KEY,
    ID_HOST INTEGER NOT NULL,
    PING_RESULT REAL,
    TIMESTAMP DATETIME NOT NULL,
    FOREIGN KEY (ID_HOST) REFERENCES TB_HOST(ID_HOST)
);

-- --- Nuevas Tablas (v2) ---

CREATE TABLE TB_ALERTA (
    ID_ALERTA INTEGER PRIMARY KEY,
    ID_HOST INTEGER NOT NULL,
    TIPO_ALERTA TEXT NOT NULL, -- Ej: 'CAIDO', 'LATENCIA_ALTA', 'LATENCIA_BAJA'
    ESTADO_ALERTA TEXT NOT NULL, -- Ej: 'ACTIVA', 'RESUELTA', 'IGNORADA'
    TIMESTAMP_INICIO DATETIME NOT NULL,
    TIMESTAMP_FIN DATETIME,
    ID_MONITOREO_INICIO INTEGER,
    FOREIGN KEY (ID_HOST) REFERENCES TB_HOST(ID_HOST)
);

CREATE TABLE TB_EVENTO_SISTEMA (
    ID_EVENTO INTEGER PRIMARY KEY,
    ID_USUARIO INTEGER,
    TIPO_EVENTO TEXT NOT NULL, -- Ej: 'HOST_CREADO', 'USUARIO_ELIMINADO'
    DETALLES_EVENTO TEXT,
    IP_ORIGEN TEXT,
    TIMESTAMP DATETIME NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIOS_DEL_SISTEMA(ID_USUARIO)
);

CREATE TABLE TB_CONFIGURACION_SISTEMA (
    CLAVE TEXT PRIMARY KEY,
    VALOR TEXT NOT NULL,
    DESCRIPCION TEXT,
    ULTIMA_MODIFICACION DATETIME
);

CREATE TABLE TB_NOTIFICACION (
    ID_NOTIFICACION INTEGER PRIMARY KEY,
    ID_ALERTA INTEGER,
    CANAL TEXT NOT NULL, -- Ej: 'EMAIL', 'SMS', 'SLACK'
    DESTINATARIO TEXT NOT NULL,
    CONTENIDO TEXT,
    ESTADO TEXT NOT NULL, -- Ej: 'ENVIADA', 'FALLIDA', 'PENDIENTE'
    TIMESTAMP DATETIME NOT NULL,
    FOREIGN KEY (ID_ALERTA) REFERENCES TB_ALERTA(ID_ALERTA)
);