from . import gerencia
from . import area
from . import responsable
from . import host
from . import alert
from . import user
from . import categoria
from . import marca
from . import modelo
from . import estado
from . import proceso
from . import sede
from . import token
from . import ubicacion
from . import monitoreo
